### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by levity**
Not sure exactly what happened here, but the 4 most recent commits in this repo don't appear to be on any branch. So when building dss-deploy in the [testchain](https://github.com/makerdao/testchain), which points to the newest of these 4 commits, we get this error:

> error: no such remote ref 3cde2158109bc085d9006d032e3fd4072129f783
> Fetched in submodule path 'testchain/lib/dss-proxy-actions/lib/dss-cdp-manager/lib/dss-deploy/lib/ds-weth', but it did not contain 3cde2158109bc085d9006d032e3fd4072129f783. Direct fetching of that commit failed.

This PR just fast-forwards `master` to include the 4 commits.

### CODE REVIEW

**Comment by asymmetric** [comment]
Not sure there was consensus about https://github.com/dapphub/ds-weth/pull/4/commits/3cde2158109bc085d9006d032e3fd4072129f783.

**Comment by levity** [comment]
I see; I missed that these were in a PR. so the alternative would be to modify dss-deploy to depend on an older commit.

**Comment by asymmetric** [comment]
Or to revert https://github.com/dapphub/ds-weth/commit/3cde2158109bc085d9006d032e3fd4072129f783 and merge #3 /cc @MrChico.

**Comment by levity** [comment]
Workaround for testchain users:
```
cd testchain/lib/dss-proxy-actions/lib/dss-cdp-manager/lib/dss-deploy/lib/ds-weth
git remote add MrChico https://github.com/MrChico/ds-weth.git
git fetch MrChico
```

**Comment by rainbreak** [comment]
One issue here was master drifting away from what is deployed on chain. With the solc updates, the bytecode of the weth that would be imported and used in e.g. tests would not be exactly the same as the on chain version.

Perhaps this is fine, or we could consider an import shim for the actual used bytecode.

**Pull request closed without merging**
