### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@d-xo We have this repo forked in makerdao and we need to add a license file. I'm sending this PR so your team can validate this is ok and then we will push the same file to our fork.
Thank you!

**Comment by d-xo** [comment]
hmmmm, I think this is gonna relicense some code (`factory.sol` and `weth.sol`). Discussing this internally and will get back to you with an answer.

**Comment by gbalabasquer** [comment]
Oh right, I just checked `we9th.sol` which had the GPL header.

**Comment by d-xo** [comment]
All good from our side 👌

**Comment by gbalabasquer** [comment]
Thank you!

**Pull request merged**
